name: HIRE-AGENT CI

on:
  push:
    branches: [ "main"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    # Copy the pre-existing .env file from the backup location to the project directory
    - name: Copy .env file from backup
      run: |
        cp /var/www/env-backups/.env.hire-agent /var/www/hire-agent-new-runner/_work/Hire-agent/Hire-agent/.env
        echo ".env file copied from backup."

    - name: Run deploy command
      run: docker-compose -f docker-compose.yml up -d --build

    - name: Remove build cache
      run: docker system prune -a -f
